---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-operator-config
  namespace: "${var.namespace}"
  labels:
    tier: operator
    app: mysql-operator
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: d922e03d.closeencounterscorps.org
