---
apiVersion: v1
kind: Secret
metadata:
  name: operator-registry
  namespace: "${var.namespace}"
  labels:
    tier: operator
    app: mysql-operator
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "${var.dockerconfigjson}"
