---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysql-operator-conn
  namespace: ${var.namespace}
  labels:
    tier: operator
    app: mysql-operator
data:
  host: "${mysql_host}"
  user: "${mysql_user}"
  password: "${mysql_password}"
  uri_args: "${mysql_uri_args}"
  default_db: "${mysql_default_db}"
